/** נוסח UI לרשומות — Stage 2C */

export const entriesCopy = {
  addButton: "הוספת רשומה",
  modalTitle: "מה לעדכן בחשבון?",
  receiveLabel: "זיכוי",
  receiveHelper: "מגדיל את הזכות שלי",
  payLabel: "חיוב",
  payHelper: "מגדיל את החובה שלי",
  amountLabel: "סכום",
  titleLabel: "פירוט קצר",
  titlePlaceholder: "לדוגמה: עבודה, מקדמה, החזר, אספקה",
  submit: "שליחה לאישור",
  submitHint:
    "הרשומה לא נכנסת ליתרה בכרטיס מיד. היא נשלחת לאישור הצד השני.",
  listTitle: "רשומות בכרטיס",
  emptyTitle: "עדיין אין רשומות בכרטיס",
  emptyBody: "הוסף רשומה כדי להתחיל לעדכן את החשבון.",
  pendingChip: "ממתין לאישור",
  pendingYourApproval: "ממתין לאישור שלך",
  pendingOtherSide: "ממתין לאישור הצד השני",
  approve: "אישור",
  reject: "דחייה",
  approving: "מאשרים…",
  rejecting: "דוחים…",
  approvedChip: "אושר",
  rejectedChip: "נדחה",
  edit: "עריכה",
  editModalTitle: "עריכת רשומה",
  editSubmit: "שמירת שינוי",
  saving: "שומרים…",
  noChange: "לא בוצע שינוי",
  cancel: "ביטול",
  cancelling: "מבטלים…",
  cancelledChip: "בוטל",
  addedByYou: "נוסף על ידך",
  addedByOther: (name: string) => `נוסף על ידי ${name}`,
} as const;
